# ADK Service Configuration Contract
# Feature: 004-storage-enhancements
# Defines how ADK services are configured and initialized

openapi: 3.0.3
info:
  title: ADK Service Configuration
  description: |
    Configuration contract for ADK SessionService and MemoryService integration.
    These are configuration schemas, not HTTP APIs.
  version: 1.0.0

components:
  schemas:
    # Session Service Configuration
    SessionServiceConfig:
      type: object
      description: Configuration for ADK SessionService
      oneOf:
        - $ref: '#/components/schemas/InMemorySessionConfig'
        - $ref: '#/components/schemas/DatabaseSessionConfig'

    InMemorySessionConfig:
      type: object
      properties:
        type:
          type: string
          const: "in_memory"
      description: |
        For development and testing only.
        ```python
        from google.adk.sessions import InMemorySessionService
        session_service = InMemorySessionService()
        ```

    DatabaseSessionConfig:
      type: object
      required: [type, db_url]
      properties:
        type:
          type: string
          const: "database"
        db_url:
          type: string
          example: "sqlite:///data/sessions.db"
          description: SQLAlchemy-compatible database URL
      description: |
        For persistent session storage.
        ```python
        from google.adk.sessions import DatabaseSessionService
        session_service = DatabaseSessionService(db_url="sqlite:///data/sessions.db")
        ```

    # Memory Service Configuration
    MemoryServiceConfig:
      type: object
      description: Configuration for ADK MemoryService
      oneOf:
        - $ref: '#/components/schemas/InMemoryMemoryConfig'
        - $ref: '#/components/schemas/VertexAIMemoryConfig'

    InMemoryMemoryConfig:
      type: object
      properties:
        type:
          type: string
          const: "in_memory"
      description: |
        For local development. No persistence, no consolidation.
        ```python
        from google.adk.memory import InMemoryMemoryService
        memory_service = InMemoryMemoryService()
        ```

    VertexAIMemoryConfig:
      type: object
      required: [type, project, location]
      properties:
        type:
          type: string
          const: "vertex_ai"
        project:
          type: string
          description: Google Cloud project ID
        location:
          type: string
          default: "us-central1"
          description: Google Cloud region
        memory_bank_id:
          type: string
          description: Optional specific memory bank ID
      description: |
        For production with cloud sync and semantic search.
        ```python
        from google.adk.memory import VertexAiMemoryBankService
        memory_service = VertexAiMemoryBankService(
            project="my-project",
            location="us-central1"
        )
        ```

    # Runner Configuration
    RunnerConfig:
      type: object
      required: [agent, app_name, session_service]
      properties:
        agent:
          type: string
          description: Reference to root agent
        app_name:
          type: string
          example: "education_app"
        session_service:
          $ref: '#/components/schemas/SessionServiceConfig'
        memory_service:
          $ref: '#/components/schemas/MemoryServiceConfig'
      description: |
        Complete runner configuration.
        ```python
        runner = Runner(
            agent=root_agent,
            app_name="education_app",
            session_service=session_service,
            memory_service=memory_service
        )
        ```

    # App Configuration (for compaction)
    AppConfig:
      type: object
      required: [name, root_agent]
      properties:
        name:
          type: string
        root_agent:
          type: string
          description: Reference to root agent
        events_compaction_config:
          $ref: '#/components/schemas/CompactionConfig'
      description: |
        App wrapper for advanced features like compaction.
        ```python
        app = App(
            name="education_app",
            root_agent=root_agent,
            events_compaction_config=EventsCompactionConfig(
                compaction_interval=6,
                overlap_size=2
            )
        )
        ```

    CompactionConfig:
      type: object
      properties:
        compaction_interval:
          type: integer
          default: 6
          description: Number of turns before compaction triggers
        overlap_size:
          type: integer
          default: 2
          description: Number of previous turns to keep for context

    # Environment Variables
    EnvironmentConfig:
      type: object
      description: Environment variables for service configuration
      properties:
        GOOGLE_API_KEY:
          type: string
          description: Required for Gemini API access
        DATA_DIR:
          type: string
          default: "./data"
          description: Directory for SQLite databases
        PDF_PATH:
          type: string
          default: "Intro.pdf"
          description: Path to educational content PDF
        GEMINI_MODEL:
          type: string
          default: "gemini-2.5-flash-lite"
          description: Model to use for agents
        VERTEX_AI_PROJECT:
          type: string
          description: Optional. If set, enables Vertex AI Memory Bank
        VERTEX_AI_LOCATION:
          type: string
          default: "us-central1"
          description: Google Cloud region for Vertex AI

    # Session Creation Request
    SessionCreateRequest:
      type: object
      required: [app_name, user_id, session_id]
      properties:
        app_name:
          type: string
        user_id:
          type: string
        session_id:
          type: string
      description: |
        Session creation/retrieval pattern.
        ```python
        try:
            session = await session_service.create_session(
                app_name=app_name,
                user_id=user_id,
                session_id=session_id
            )
        except:
            session = await session_service.get_session(
                app_name=app_name,
                user_id=user_id,
                session_id=session_id
            )
        ```

    # Memory Tools Configuration
    MemoryToolsConfig:
      type: object
      properties:
        strategy:
          type: string
          enum: [reactive, proactive]
          description: |
            reactive: Agent decides when to load memory (load_memory)
            proactive: Memory loaded before every turn (preload_memory)
        auto_save:
          type: boolean
          default: true
          description: Whether to use after_agent_callback for auto-save
      description: |
        Memory tool selection.
        ```python
        # Reactive (cost-efficient)
        from google.adk.tools import load_memory
        agent = LlmAgent(tools=[load_memory])

        # Proactive (guaranteed context)
        from google.adk.tools import preload_memory
        agent = LlmAgent(tools=[preload_memory])

        # Auto-save callback
        async def auto_save_to_memory(callback_context):
            await callback_context._invocation_context.memory_service.add_session_to_memory(
                callback_context._invocation_context.session
            )

        agent = LlmAgent(
            tools=[preload_memory],
            after_agent_callback=auto_save_to_memory
        )
        ```
