# Storage Service API Contract
# Feature: 004-storage-enhancements
# This defines the Python API contract for the StorageService class

openapi: 3.0.3
info:
  title: Storage Service Internal API
  description: |
    Python API contract for adk/storage.py StorageService class.
    These are method signatures, not HTTP endpoints.
  version: 1.0.0

paths:
  # Session Persistence (FR-001, FR-002, FR-003)
  /sessions:
    get:
      operationId: list_sessions
      summary: List available sessions for a user (FR-003)
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            default: 10
        - name: include_completed
          in: query
          schema:
            type: boolean
            default: true
      responses:
        '200':
          description: List of session summaries
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SessionSummary'

  # User Memory (FR-004, FR-005)
  /user-memories:
    post:
      operationId: save_user_memory
      summary: Store a learned fact about the user (FR-004)
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserMemoryInput'
      responses:
        '201':
          description: Memory saved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserMemory'
    get:
      operationId: get_user_memories
      summary: Retrieve relevant memories for context (FR-005)
      parameters:
        - name: fact_type
          in: query
          schema:
            type: string
            enum: [preference, interest, difficulty_area, learning_style, behavior]
        - name: active_only
          in: query
          schema:
            type: boolean
            default: true
      responses:
        '200':
          description: List of user memories
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserMemory'

  # Knowledge Graph (FR-006, FR-007, FR-008)
  /concepts/{concept_name}/prerequisites:
    get:
      operationId: get_prerequisites
      summary: Get prerequisite concepts (FR-007)
      parameters:
        - name: concept_name
          in: path
          required: true
          schema:
            type: string
        - name: max_depth
          in: query
          schema:
            type: integer
            default: 5
            maximum: 10
      responses:
        '200':
          description: Ordered list of prerequisites
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PrerequisiteResult'

  /concepts/{concept_name}/enabled:
    get:
      operationId: get_enabled_concepts
      summary: Get concepts enabled by mastering this one (FR-007)
      parameters:
        - name: concept_name
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of enabled concepts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EnabledConcept'

  /concepts/path:
    get:
      operationId: get_learning_path
      summary: Find shortest learning path between concepts (FR-008)
      parameters:
        - name: from
          in: query
          required: true
          schema:
            type: string
        - name: to
          in: query
          required: true
          schema:
            type: string
        - name: max_depth
          in: query
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: Ordered learning path
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LearningPath'
        '404':
          description: No path found between concepts

  # Sync (FR-009, FR-010, FR-011)
  /sync/status:
    get:
      operationId: get_sync_status
      summary: Get current sync status for device (FR-009)
      responses:
        '200':
          description: Sync state
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SyncState'

  /sync/push:
    post:
      operationId: push_changes
      summary: Push local changes to cloud (FR-009)
      responses:
        '200':
          description: Changes pushed
          content:
            application/json:
              schema:
                type: object
                properties:
                  pushed_count:
                    type: integer
                  conflicts:
                    type: array
                    items:
                      $ref: '#/components/schemas/SyncConflict'

  /sync/pull:
    post:
      operationId: pull_changes
      summary: Pull remote changes (FR-010)
      responses:
        '200':
          description: Changes pulled
          content:
            application/json:
              schema:
                type: object
                properties:
                  pulled_count:
                    type: integer
                  applied_count:
                    type: integer

  # Export/Import (FR-012, FR-013, FR-014)
  /export:
    get:
      operationId: export_progress
      summary: Export all user data (FR-012)
      responses:
        '200':
          description: Complete data export
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataExport'

  /import:
    post:
      operationId: import_progress
      summary: Import user data from export (FR-013)
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DataExport'
      responses:
        '200':
          description: Import successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  imported_count:
                    type: object
                    additionalProperties:
                      type: integer
                  warnings:
                    type: array
                    items:
                      type: string
        '400':
          description: Import failed - version incompatible or data invalid

  # Migration (FR-015, FR-016)
  /migrate:
    post:
      operationId: migrate_database
      summary: Run pending migrations (FR-015)
      responses:
        '200':
          description: Migration successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  from_version:
                    type: string
                  to_version:
                    type: string
                  migrations_applied:
                    type: array
                    items:
                      type: string

  /migrate/rollback:
    post:
      operationId: rollback_migration
      summary: Rollback last migration (FR-016)
      responses:
        '200':
          description: Rollback successful
        '400':
          description: No backup available

components:
  schemas:
    SessionSummary:
      type: object
      required: [session_id, started_at, message_count]
      properties:
        session_id:
          type: string
        started_at:
          type: string
          format: date-time
        last_activity:
          type: string
          format: date-time
        message_count:
          type: integer
        topic:
          type: string
        is_completed:
          type: boolean

    UserMemoryInput:
      type: object
      required: [fact_type, fact_key, fact_value]
      properties:
        fact_type:
          type: string
          enum: [preference, interest, difficulty_area, learning_style, behavior]
        fact_key:
          type: string
          example: "preferred_explanation_style"
        fact_value:
          type: string
          example: "step-by-step"
        source_session_id:
          type: string

    UserMemory:
      allOf:
        - $ref: '#/components/schemas/UserMemoryInput'
        - type: object
          properties:
            id:
              type: integer
            user_id:
              type: string
            first_mentioned:
              type: string
              format: date-time
            last_confirmed:
              type: string
              format: date-time
            confidence:
              type: number
              minimum: 0
              maximum: 1
            is_active:
              type: boolean

    PrerequisiteResult:
      type: object
      properties:
        concept:
          type: string
        depth:
          type: integer
          description: Distance from original concept
        path:
          type: string
          description: Learning path representation

    EnabledConcept:
      type: object
      properties:
        concept:
          type: string
        relationship:
          type: string
          enum: [depends-on, builds-on]
        rationale:
          type: string

    LearningPath:
      type: object
      properties:
        path:
          type: array
          items:
            type: string
        total_steps:
          type: integer
        estimated_time:
          type: string
          description: Estimated learning time

    SyncState:
      type: object
      properties:
        device_id:
          type: string
        device_name:
          type: string
        sync_status:
          type: string
          enum: [synced, pending, conflict, error]
        last_local_change:
          type: string
          format: date-time
        last_remote_sync:
          type: string
          format: date-time
        pending_count:
          type: integer
        last_error:
          type: string

    SyncConflict:
      type: object
      properties:
        entity_type:
          type: string
        entity_id:
          type: string
        local_value:
          type: object
        remote_value:
          type: object
        resolution:
          type: string
          enum: [local_wins, remote_wins]
        resolved_at:
          type: string
          format: date-time

    DataExport:
      type: object
      required: [version, user_id, exported_at]
      properties:
        version:
          type: string
          example: "1.0.0"
        user_id:
          type: string
        exported_at:
          type: string
          format: date-time
        stats:
          type: object
        quiz_history:
          type: array
          items:
            type: object
        concept_mastery:
          type: array
          items:
            type: object
        knowledge_gaps:
          type: array
          items:
            type: object
        user_memories:
          type: array
          items:
            $ref: '#/components/schemas/UserMemory'
        session_summaries:
          type: array
          items:
            $ref: '#/components/schemas/SessionSummary'
        checksum:
          type: string
          description: SHA256 for integrity verification
